
export default {
  login: "ctsstc",
  id: 416814,
  node_id: "MDQ6VXNlcjQxNjgxNA==",
  avatar_url: "https://avatars3.githubusercontent.com/u/416814?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ctsstc",
  html_url: "https://github.com/ctsstc",
  followers_url: "https://api.github.com/users/ctsstc/followers",
  following_url: "https://api.github.com/users/ctsstc/following{/other_user}",
  gists_url: "https://api.github.com/users/ctsstc/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ctsstc/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ctsstc/subscriptions",
  organizations_url: "https://api.github.com/users/ctsstc/orgs",
  repos_url: "https://api.github.com/users/ctsstc/repos",
  events_url: "https://api.github.com/users/ctsstc/events{/privacy}",
  received_events_url: "https://api.github.com/users/ctsstc/received_events",
  type: "User",
  site_admin: false,
  name: "Cody Swartz",
  company: "Logic Happens",
  blog: "http://codyswartz.us/",
  location: "Bend, Oregon",
  email: null,
  hireable: true,
  bio: null,
  public_repos: 39,
  public_gists: 6,
  followers: 28,
  following: 131,
  created_at: "2010-09-26T21:31:50Z",
  updated_at: "2018-09-05T16:21:19Z"
} as IGithubProfile;
